apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influx:8086
    database: travelToProd
    user: admin
    secureJsonData:
      password: adminadmin
    jsonData:
      httpMode: GET
      timeInterval: 15s
      version: InfluxQL
    version: 1